<?xml version="1.0"?>
<!-- Description of the tas_car. -->

<robot name="tas_car" xmlns:xacro="http://www.ros.org/wiki/xacro"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    <!-- Physical constants. -->
    <xacro:property name="degrees_45" value="0.785398163" />
    <xacro:property name="degrees_90" value="1.57079633" />
    <xacro:property name="PI"         value="3.1415926535897931" />

    <!-- Chassis. -->
    <xacro:property name="chassis_length" value="0.346" />
    <xacro:property name="chassis_width"  value="0.17" />
    <xacro:property name="chassis_height" value="0.095" />
    <xacro:property name="chassis_mass"   value="3" />

    <!-- hub_diameter and tire_diameter are the diameters of the hub and tire,
       respectively. hex_hub_depth is the distance that the hex hub is
       inset from the outer edge of the tire. It is set so that each wheel
       is a "zero offset" wheel. hex_hub_depth = tire_width / 2 -
       axle_length. -->
    <xacro:property name="hub_diameter" value="0.09652"/>
    <xacro:property name="tire_radius" value="0.0695" />
    <xacro:property name="tire_diameter" value="${2*tire_radius}"/>
    <xacro:property name="tire_width" value="0.0889"/>
    <xacro:property name="hex_hub_depth" value="0.01445"/>
    <xacro:property name="wheel_mass" value="0.3"/>
    <xacro:property name="wheel_pos" value="0.179"/>

    <!-- hex_hub_dist is the distance between left and right hex hubs when
       the shock absorbers are fully extended. axle_length is the distance
       from a U joint to the corresponding hex hub. wheel_travel is the
       vertical wheel travel. -->
    <xacro:property name="wheelbase" value="${chassis_length}"/>
    <xacro:property name="hex_hub_dist" value="0.365"/>
    <xacro:property name="axle_length" value="0.03"/>
    <xacro:property name="wheel_travel" value="0.084"/>
    <xacro:property name="shock_z_offset" value="0.0055"/>

    <!-- TODO get shock sprint constant, default used here -->
    <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
       shock_stroke is 0.028575 meters. shock_spring_constant, an approximation
       of the shock absorber spring's constant, is
       437.817 N/m. -->
    <xacro:property name="shock_eff_limit" value="12.5106"/>
    <xacro:property name="shock_vel_limit" value="1000"/>

    <!-- TODO get correct motor specifications -->
    <!-- The specifications for a Titan(R) 550 motor could not be found, so the
       stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor was used instead.

       num_spur_gear_teeth = 68
       num_pinion_gear_teeth = 19
       final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
         5.22 = 18.68
       stall_torque = 0.549 N m
       axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
         5.12766 N m

       max_speed = 40 mph (30+ mph) = 17.8816 m/s
       axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_diameter)) =
         244.8696 rad/s -->
    <xacro:property name="axle_eff_limit" value="5.12766"/>
    <xacro:property name="axle_vel_limit" value="244.8696"/>

    <!-- TODO get correct servo specifications -->
    <!-- These constants are used to simulate a Traxxas 2056 servo operated at
       6 V. servo_stall_torque is measured in N m. servo_no_load_speed is
       measured in rad/s. -->
    <xacro:property name="servo_stall_torque" value="0.5649"/>
    <xacro:property name="servo_no_load_speed" value="4.553"/>

    <!-- Laser. -->
    <xacro:property name="laser_size" value="0.05"/>
    <xacro:property name="laser_mass" value="0.1"/>

    <!-- Include files. -->
    <xacro:include filename="$(find tas_car_description)/urdf/include/materials.xacro" />
    <xacro:include filename="$(find tas_car_description)/urdf/include/macros.xacro" />
    <xacro:include filename="$(find tas_car_description)/urdf/include/gazebo_params.gazebo" />

<!-- Build the robot. -->
    <!-- Base link. -->
    <xacro:base_link />

    <!-- Chassis. -->
    <xacro:chassis />

    <!-- Wheels -->
    <xacro:front_wheel  lr_prefix="left" 
                        fr_prefix="front"
                        lr_reflect="1" 
                        fr_reflect="1"
    />

    <xacro:front_wheel  lr_prefix="right" 
                        fr_prefix="front"
                        lr_reflect="-1" 
                        fr_reflect="1"
    />

    <xacro:rear_wheel   lr_prefix="left" 
                        fr_prefix="rear"
                        lr_reflect="1" 
                        fr_reflect="-1"
    />

    <xacro:rear_wheel   lr_prefix="right" 
                        fr_prefix="rear"
                        lr_reflect="-1" 
                        fr_reflect="-1"
    />

    <!-- Laser scanner. -->
    <xacro:hokuyo_laser />

    
    <!-- imu -->
    <xacro:imu_link/>
  
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
    </gazebo>

    <gazebo reference="chassis">
      <material>Gazebo/Orange</material>
    </gazebo>
</robot>
